import puppeteer from '/Users/seb/Documents/ChatGPT/Project BellKeeper/recipe-reference/node_modules/puppeteer/lib/puppeteer/puppeteer.js';
import ffmpeg from '/Users/seb/Documents/ChatGPT/Project BellKeeper/setup-tools/node_modules/ffmpeg-static/index.js';
import fs from 'node:fs/promises';
const out=new URL('./',import.meta.url);const browser=await puppeteer.launch({headless:true});const p=await browser.newPage();const result={build:'b5eb674ac6de701e200da9dd48678966bbb761e9',errors:[],observations:[],kind:'normal inputs; telemetry read only; headless emulated phone, no physical performance/audio claim'};p.on('pageerror',e=>result.errors.push(e.message));const sleep=ms=>new Promise(r=>setTimeout(r,ms));const read=()=>p.evaluate(()=>window.__GAME__);async function log(label){result.observations.push({label,state:await read(),caption:await p.$eval('#caption',e=>e.textContent)});}async function shot(name){await p.screenshot({path:new URL(name+'.png',out).pathname});}
async function record(name,task){const rec=await p.screencast({ffmpegPath:ffmpeg,fps:20});const chunks=[];rec.on('data',c=>chunks.push(c));try{await task();}finally{await rec.stop();await fs.writeFile(new URL(name+'.webm',out),Buffer.concat(chunks));}}
let mobile=false,client;async function go(x,z){for(let i=0;i<160;i++){const s=await read();const dx=x-s.pos[0],dz=z-s.pos[1];if(Math.hypot(dx,dz)<.26)return;const sx=dx*.788-dz*.615,sy=-dx*.615-dz*.788;if(mobile){const r=await p.$eval('#stick',e=>{const a=e.getBoundingClientRect();return{x:a.x+a.width/2,y:a.y+a.height/2}});const m=Math.hypot(sx,sy);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x,y:r.y}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+sx/m*36,y:r.y-sy/m*36}]});await sleep(200);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{const keys=[];if(Math.abs(sx)>.14)keys.push(sx>0?'KeyD':'KeyA');if(Math.abs(sy)>.14)keys.push(sy>0?'KeyW':'KeyS');for(const k of keys)await p.keyboard.down(k);await sleep(150);for(const k of keys)await p.keyboard.up(k);}}throw Error('route timeout '+x+','+z);}
try{
await p.setViewport({width:1280,height:800});await p.goto('http://127.0.0.1:4173/the-last-bellkeeper/');await p.waitForFunction(()=>window.__READY__);await p.click('#startb');
await record('closed-gate-crossing',async()=>{await go(4.45,-1.7);await log('gate front closed');await shot('gate-front');await go(5.12,-2.80);await log('gate rear still closed');await shot('gate-rear');});
}catch(e){result.testError=e.stack;}finally{await fs.writeFile(new URL('gate-result.json',out),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();}
