import puppeteer from '/Users/seb/Documents/ChatGPT/Project BellKeeper/recipe-reference/node_modules/puppeteer/lib/puppeteer/puppeteer.js';
import fs from 'node:fs/promises';
const out='evidence/test-scene';await fs.mkdir(out,{recursive:true});const browser=await puppeteer.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const misses=[];page.on('response',r=>{if(r.status()>=400)misses.push(r.url())});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{await page.setViewport({width:1440,height:900});await page.goto('http://127.0.0.1:4173/the-last-bellkeeper/');await page.waitForFunction(()=>window.__READY__,{timeout:20000});await page.screenshot({path:out+'/title.png'});await page.click('#startb');await sleep(300);await page.screenshot({path:out+'/start.png'});
 const initial=await page.evaluate(()=>window.__GAME__);
 async function go(x,z){for(let i=0;i<80;i++){const g=await page.evaluate(()=>window.__GAME__);const dx=x-g.pos[0],dz=z-g.pos[1];if(Math.hypot(dx,dz)<.28)return;const sx=dx*.788-dz*.615,sy=-dx*.615-dz*.788;const k=[];if(Math.abs(sx)>.16)k.push(sx>0?'KeyD':'KeyA');if(Math.abs(sy)>.16)k.push(sy>0?'KeyW':'KeyS');for(const a of k)await page.keyboard.down(a);await sleep(130);for(const a of k)await page.keyboard.up(a);}throw Error('Route failed '+x+','+z);}
 await page.keyboard.press('Space');const emptyMiss=await page.evaluate(()=>window.__GAME__.charged===false);
 await go(-3,1.4);await page.keyboard.press('Space');await sleep(850);const captured=await page.evaluate(()=>window.__GAME__.charged);await page.screenshot({path:out+'/captured.png'});
 await page.keyboard.press('Space');await sleep(900);const retained=await page.evaluate(()=>window.__GAME__.charged&&!window.__GAME__.restored);
 await go(1.3,-.5);await page.keyboard.press('Space');await sleep(1700);const restored=await page.evaluate(()=>window.__GAME__.restored);await page.screenshot({path:out+'/restored.png'});
 await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__GAME__.paused);const paused=await page.evaluate(()=>window.__GAME__.paused);await page.click('#reset');await sleep(200);const reset=await page.evaluate(()=>!window.__GAME__.restored&&!window.__GAME__.charged);const final=await page.evaluate(()=>window.__GAME__);
 await page.setViewport({width:430,height:932,isMobile:true,hasTouch:true,deviceScaleFactor:1});await page.reload();await page.waitForFunction(()=>window.__READY__);await page.tap('#startb');await sleep(300);await page.screenshot({path:out+'/phone.png'});const before=await page.evaluate(()=>window.__GAME__.pos);const client=await page.createCDPSession();await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:82,y:845}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:82,y:809}]});await sleep(1100);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const after=await page.evaluate(()=>window.__GAME__.pos);const touchDistance=Math.hypot(after[0]-before[0],after[1]-before[1]);
 const result={kind:'real-input scene regression; emulation not physical phone',emptyMiss,captured,retained,restored,paused,reset,touchDistance,initial,final,errors,misses};await fs.writeFile(out+'/test-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!emptyMiss||!captured||!retained||!restored||!paused||!reset||touchDistance<1||errors.length||misses.length)process.exitCode=1;
}finally{await browser.close();}
